### PR TITLE
Simple way to get baseDir

### PR DESCRIPTION
**Pull request by 123fork**
I tried to use ./upload/config.php, but it's a sick headache.. (:

### CODE REVIEW

**Review by rodrigomanara — COMMENTED** [review]
does it give the path when u are also working on OC 2.*

**Comment by 123fork** [comment]
Hm.. I think yes. Why not? 

Also for upload_dir you can use this:

composer config extra.opencart.upload_dir './upload/'

$extra = $event->getComposer()->getPackage()->getExtra();
$opencart_upload_dir = $extra['opencart']['upload_dir'];

**Comment by 123fork** [comment]
And this
  $filesystem = new \Composer\Util\Filesystem;
  path_without_dots = $filesystem->normalizePath($path);

**Comment by rodrigomanara** [comment]
Ok, before  I merge I will checkout your patch. thanks for your help
 
 

    On Tuesday, 1 August 2017, 14:39, 123fork <notifications@github.com> wrote:
 

 Hm.. I think yes. Why not?Also for upload_dir you can you this:composer config extra.opencart.upload_dir './upload/'$extra = $event->getComposer()->getPackage()->getExtra();
$opencart_upload_dir = $extra['opencart']['upload_dir'];—

**Pull request merged**
